package practica5;

public enum FilterFields {
	EPISODE_TITLE,
	EPISODE_SEASON_GREATER_THAN,
	EPISODE_SEASON_LESSER_THAN,
	EPISODE_SEASON_EQUAL_THAN,
	EPISODE_RATING_GREATER_THAN,
	LINE_CHARACTER,
	LINE_SPOKEN_WORDS
}
